# Preprocessing Step

In [2]:
import pickle 
import numpy as np

In [3]:
"""
Extracting data into a file
"""
data = None
labels = []
for i in range(5):
    j = i + 1
    file = "images/data_batch_" + str(j)
    with open(file, 'rb') as fo:
        print("extracting file "+file+"...")
        dict = pickle.load(fo, encoding='bytes')
        temp_data = dict[b'data']
        try:
            data = np.concatenate((data, temp_data), axis=0)
        except:
            data = temp_data
        labels = labels + dict[b'labels']

print("Finished Extracting Features")
print(np.shape(data))
        

extracting file images/data_batch_1...
extracting file images/data_batch_2...
extracting file images/data_batch_3...
extracting file images/data_batch_4...
extracting file images/data_batch_5...
Finished Extracting Features
(50000, 3072)


# QDA

In [4]:
"""
Define Parameters 
"""
mu = [[0 for i in range(3027)] for i in range(10)] # initializing means 
sigmas = [[0 for i in range(3027)] for i in range(10)] # initializing variances
pi = [[0 for i in range(3027)] for i in range(10)] # initializing prior probabiltiies 

In [5]:
"""
Create Dictionary of indexes sorted by label 
"""
label_dictionary = {} 
for index,label in enumerate(labels):
    if label not in label_dictionary:
        label_dictionary[label] = [index]
    else:
        label_dictionary[label].append(index)

In [ ]:
"""
Learn Parameters
"""
for label in label_dictionary:
    for imageIndex in label_dictionary[label]:
        image = data[imageIndex]
        print(image)
        exit()
print(pi[0][:10])
    
            

[ 59  43  50 ... 140  84  72]
[ 23  47  52 ... 184 183 186]
[ 86  96 115 ...  30  32  32]
[126 102 117 ... 124 174 164]
[162 164 169 ... 178 181 183]
[229 227 208 ... 164 154 184]
[246 252 249 ... 143 149 150]
[3 3 2 ... 3 2 0]
[ 0  0  0 ... 25 22  1]
[172 184 197 ... 109  96  79]
[180 178 184 ...  86  73  70]
[255 251 251 ... 233 245 252]
[67 65 61 ... 56 69 60]
[115 105 101 ...  91 144 124]
[162 156 140 ... 197 186 176]
[176 168 167 ... 151 148 147]
[13  9 10 ... 87 69 79]
[85 85 86 ... 38 34 33]
[105  99 111 ... 151 173 196]
[103 127 109 ... 181 141  76]
[187 183 184 ... 126 122 123]
[180 180 180 ... 156 145 142]
[22 63 81 ...  0  0  0]
[224 164 169 ...  50  64  72]
[146 145 144 ... 142 133 119]
[106  96  89 ...  67  60  57]
[249 246 249 ... 249 249 248]
[123 124 127 ...  30  28  47]
[ 74  79  90 ...  98  98 102]
[ 51  47  47 ... 117 161 156]
[24 19 24 ... 59 88 92]
[126 161 195 ...  84  90  97]
[ 55  54  51 ... 146 139 138]
[193 132 118 ...  10  16  16]
[ 52  54  57 ... 176 176 176

[  0   1   0 ... 104 109 104]
[175 158 164 ...  79  81  80]
[122 127 133 ...  75  94  79]
[126 132 150 ...  35  19  12]
[116 104  87 ...  14  14  15]
[103  71  87 ... 153 151 143]
[10 11 10 ... 25 28 29]
[215 209 208 ... 142 144 141]
[53 76 66 ... 40 37 47]
[ 95  93 132 ...  58  68  43]
[122 132 117 ...  39  27  26]
[105  95  94 ...  17  27  45]
[188 177 179 ... 153 143 133]
[ 85  60  71 ... 158 121 106]
[  1   1   1 ... 210 185 184]
[ 78  85  85 ... 130 122 117]
[92 85 80 ... 72 65 89]
[143 139 138 ... 194 193 189]
[136 140 128 ... 135 136 150]
[86 85 85 ... 45 42 44]
[ 76  65  89 ...  87 180 244]
[166 169 159 ... 150 134 133]
[144 146 117 ... 101 113 118]
[127 120 136 ...  77  65  87]
[141 109 136 ...  49  46  48]
[171 169 164 ... 118 108 114]
[72 84 89 ... 68 70 65]
[255 255 255 ... 255 255 255]
[255 253 253 ... 253 253 252]
[207 205 177 ... 115 114 114]
[190 156 188 ... 161 166 170]
[ 18  17  16 ...  98 112 119]
[180 166 152 ... 101  75  58]
[136 152 132 ...  33  32  36]
[207 209 2

[63 71 83 ... 37 33 32]
[29 32 30 ... 40 48 54]
[ 13   8   6 ... 184 182 180]
[102  96  99 ...  88  90  90]
[ 56  84  85 ...  76 112 145]
[134 100 107 ...  62 117 105]
[253 252 252 ... 252 252 252]
[42 46 51 ... 97 92 89]
[ 70  87 114 ...  52  57  50]
[1 1 1 ... 9 1 1]
[26 30 45 ... 95 98 98]
[137 168 169 ... 120 117 116]
[113 169 157 ...  66  64  74]
[255 252 252 ... 255 255 255]
[221 218 218 ... 223 224 227]
[121 134 146 ... 219 219 223]
[255 253 253 ... 190 196 198]
[ 6 18 17 ... 72 82 61]
[ 46  49  52 ... 122  95  77]
[107 148 164 ...  63  60  44]
[126 132 143 ... 117 115 119]
[251 232 210 ... 162 172 217]
[176 177 166 ...  73  62  40]
[243 241 247 ...  82  88  86]
[45 31 18 ... 52 26 45]
[163 151 192 ...  92  88 101]
[228 201 198 ... 222 233 251]
[140 134 133 ...   2   1   1]
[ 53  46  48 ... 178 179 181]
[57 57 58 ... 71 70 68]
[168 163 161 ... 141 142 137]
[255 251 252 ... 251 251 255]
[153 156 160 ...  45  34  27]
[ 4  4  5 ... 78 83 88]
[252 251 252 ... 217 242 251]
[ 83  73  

[3 3 3 ... 1 1 1]
[ 61  99 120 ... 161 172 167]
[119 109 127 ...  91 106  78]
[ 4 13 13 ... 18 10  5]
[ 12  10  11 ... 110 118  68]
[159 147 150 ...  76  75  76]
[155 153 155 ... 137 148 143]
[116 116 119 ...  99 101 106]
[154 142 164 ... 116  90 115]
[157 170 167 ...   3   4   3]
[72 73 81 ... 43 52 45]
[200 195 184 ...  32  20  17]
[142 141 150 ... 210 198 198]
[23 11  1 ...  1  8  6]
[88 94 95 ... 48 54 55]
[ 55  47  65 ...  98 106 140]
[205 205 231 ... 103 102  97]
[125 122 122 ...  10  13  19]
[243 240 240 ... 120 122 126]
[118 120 124 ... 108 111 111]
[ 0  1  1 ... 52 65 81]
[123 116 115 ...  40  18  24]
[168 159 150 ...  92  64  64]
[ 56  91 103 ...  66  90 137]
[176 183 196 ...  81 120 125]
[90 42  8 ... 94 89 93]
[124  99 127 ...  20  21  42]
[154 156 156 ...  64  60  83]
[235 241 248 ... 104 102 103]
[17 22 25 ...  7 10  8]
[110 109  94 ...  94 140 158]
[26 23 21 ... 27 29 33]
[ 32  63 143 ...  96  92  85]
[41 46 53 ... 14 23 32]
[127 124 110 ...  75  61  62]
[ 75  87  90 ...

[ 95  98  94 ... 252 252 252]
[147 134 121 ... 180 163 159]
[147 164 138 ... 141 130  96]
[255 254 254 ... 255 255 255]
[255 255 255 ... 255 255 255]
[ 67  62  63 ... 112 121 121]
[ 29  30  25 ... 153 160 172]
[86 91 99 ... 76 73 59]
[117 117 113 ... 101  67  84]
[125 133 123 ... 130 154 166]
[20 17 20 ... 58 46 58]
[154 181 193 ...  44  62 118]
[231 153 148 ... 237 233 250]
[ 71 120 128 ...  87  68  60]
[138 142 122 ... 128 139 128]
[ 30  40  36 ... 127 122 108]
[51 51 51 ... 75 77 56]
[ 30  23  23 ... 102 101 105]
[81 88 87 ... 46 44 42]
[99 79 44 ... 21 24 33]
[166 159 155 ... 156 159 155]
[178 173 164 ... 212 225 226]
[106 108 100 ...  66  50  70]
[ 41  45  54 ... 118 116 131]
[100 122 125 ... 183 176 172]
[ 1  1 16 ... 59 79 62]
[  1   1   1 ... 134 127 115]
[193 196 208 ... 233 231 227]
[237 231 228 ... 206 207 209]
[ 22  23  23 ... 118 114 108]
[203 209 206 ...  11  13   8]
[ 93  99 115 ... 119 148 133]
[ 74  73  79 ...  47  81 124]
[ 48  31  28 ...  58  82 103]
[41 31 27 ... 54

[ 67  37  49 ...  78 137 173]
[13  9  5 ... 52 49 57]
[253 248 248 ... 239 237 237]
[ 63  68  68 ... 121 128 134]
[40 43 51 ... 46 46 48]
[255 255 255 ... 253 253 253]
[113 151 166 ... 196  98  62]
[139 143 146 ... 112  98  95]
[18 14 13 ...  6  7 11]
[112 111 111 ... 187 187 187]
[255 252 250 ... 253 254 255]
[101 112 116 ... 134 136 134]
[102  46  25 ...  98  64  55]
[ 6 16 14 ... 65 68 30]
[147 143 143 ... 147 107 103]
[147 151 152 ...  86  80  74]
[191 179 168 ... 143 131 148]
[244 228 242 ... 129  97 100]
[ 75  70  75 ... 186 198 194]
[ 44  83 124 ...  23  23  13]
[ 95 116 114 ...  72  61  43]
[212 181 162 ...  69  68  74]
[80 91 90 ... 76 70 40]
[116 124 125 ...  20  30  17]
[19 14  8 ... 33 43 20]
[ 55  13 113 ... 107 106 109]
[117 112 112 ...  50  51  74]
[72 67 75 ... 30 31 30]
[118 122 122 ...  67  83  97]
[101 103 112 ... 110 125 133]
[114 114 114 ... 132 133 135]
[82 79 84 ... 76 63 43]
[255 252 252 ... 252 252 252]
[ 25  21  16 ...  91 130 139]
[149 159 160 ...  55  40  36

[  5   5   5 ... 147 141 137]
[126 130 140 ...  30  23  22]
[112 150 161 ...  62  60  66]
[201 201 203 ... 124 110 107]
[22 21 21 ... 58 65 67]
[ 26  45  53 ... 102 100 106]
[150 133 140 ...  50  53  56]
[80 69 52 ... 68 66 63]
[ 40  41  43 ... 127 105  89]
[ 79  75  93 ...  54  80 110]
[ 95  67  43 ...  82  88 100]
[148 144 144 ...  56  50  43]
[207 220 231 ... 180 184 179]
[ 52  65  80 ...  59  91 138]
[31 39 94 ... 74 87 82]
[244 241 242 ... 192 191 189]
[167 176 151 ... 150 199 213]
[255 255 255 ... 255 255 255]
[160 182 174 ...  74  34  29]
[255 255 255 ... 255 255 255]
[117 134 159 ... 106 103  95]
[164  77  61 ...  10   8   7]
[135 139 141 ...  64  53  55]
[30 31 31 ... 56 56 56]
[125  91 147 ...  42  51  47]
[106 101  98 ... 124 117 126]
[181 179 160 ... 225 222 222]
[209 207 207 ... 255 255 255]
[147 157 155 ... 122 106 101]
[145 132 148 ... 135 137 136]
[132 121 122 ... 127 120 126]
[ 23  23  23 ... 116 115 105]
[116 116 120 ... 113 108  73]
[67 81 96 ... 72 70 77]
[47 59 62 

[133 152 208 ... 167 135  87]
[208 165 136 ... 109 103  96]
[233 242 244 ...  41  47  47]
[114 129 133 ...  92  73  76]
[32 44 39 ...  9 18 21]
[ 24  18  18 ... 197 197 199]
[ 14  19  13 ... 174 161 156]
[ 93  80  82 ... 105 136 114]
[177 177 171 ...  83  82  91]
[255 255 255 ... 255 255 255]
[18 70 95 ... 56 69 53]
[ 2  2  2 ... 20 39 17]
[121  71  26 ... 198 178 168]
[160 139 134 ...  65  84  91]
[156 136 112 ... 185 181 204]
[63 73 71 ...  7 12 12]
[104  90 103 ...   7  11   7]
[149 128  84 ...  33  21  35]
[118 156 135 ...  56  43  16]
[ 57  70 109 ...  34  50  56]
[37 29 27 ... 37 29 26]
[46 66 74 ... 11 10 13]
[142 153 145 ...   8  18  30]
[  4   4   4 ... 145 133 132]
[117 122 123 ... 131 137 120]
[153 167 172 ... 134 133 139]
[ 17  14  24 ... 208 228 223]
[146 150 138 ... 135  94  66]
[ 93  97 114 ...  45  39  39]
[210 204 142 ... 125 134 103]
[63 62 63 ... 59 61 61]
[102  94 125 ...  88  88  94]
[ 91  87 105 ...  43  30  24]
[0 0 0 ... 0 0 0]
[ 13   0   0 ... 162 161 158]
[174

[130 121 127 ... 225 223 223]
[129 133 137 ...  69  75  75]
[255 255 255 ... 255 255 255]
[123 126 129 ... 177 183 183]
[174 155 162 ...  70  72  72]
[232 228 225 ... 159 159 159]
[109 108 108 ...  78  81  87]
[255 252 252 ... 214 249 252]
[173 171 168 ...  89 107 116]
[255 253 253 ... 253 253 253]
[239 239 238 ... 204 216 230]
[ 79  79  79 ... 128 130 129]
[255 255 253 ...  74  85  90]
[ 98  96  98 ... 136 166 202]
[134 140 148 ... 142 136 136]
[210 208 208 ... 190 191 192]
[243 241 241 ... 166 161 162]
[ 51  50  61 ...  98 110 114]
[ 89 110 122 ...  60  55  55]
[255 255 255 ... 253 254 254]
[245 243 244 ...  57  55  55]
[203 197 200 ... 135 135 141]
[0 0 0 ... 0 0 0]
[228 228 230 ... 255 255 255]
[221 194 141 ...  73  69  73]
[ 86 101  92 ... 164 164 163]
[24 20 39 ... 51 62 68]
[216 222 231 ... 109 108 105]
[91 76 81 ... 86 82 85]
[255 252 252 ... 252 252 252]
[237 236 239 ...  95  78  80]
[108 109 110 ... 238 239 234]
[165 161 162 ... 154 151 152]
[236 230 233 ... 102 103  91]
[245

[114 114 114 ... 169 170 169]
[30 55 66 ... 92 93 91]
[ 64  57  75 ... 254 254 254]
[59 59 59 ... 51 51 53]
[173 173 177 ...  79  83 108]
[213 215 216 ...  72  70  65]
[237 235 235 ...  63  70  86]
[148 148 115 ... 146 146 147]
[ 69  59  59 ... 153 151 149]
[255 255 255 ... 215 217 227]
[73 73 69 ... 55 54 45]
[182 184 188 ...  83 123 150]
[255 252 253 ... 253 253 253]
[255 252 252 ... 130 128 123]
[255 252 250 ... 255 255 255]
[ 45  46  48 ... 113 106 104]
[200 202 203 ... 120 125 128]
[240 242 243 ... 252 252 252]
[ 92  89  89 ... 106 105 105]
[255 255 255 ... 152 152 146]
[169 143 147 ... 124 125 120]
[58 58 59 ... 23 20 20]
[128 131 134 ... 136 119 101]
[227 223 223 ... 163 160 156]
[249 247 248 ... 136 118 148]
[ 92  91  89 ... 146 154 175]
[255 251 252 ... 255 254 253]
[140 133 141 ... 241 245 170]
[ 21  20  20 ... 118 121 114]
[255 254 254 ... 255 255 255]
[255 252 253 ... 147 144 149]
[173 174 175 ... 115 121 144]
[187 188 189 ... 144 158 154]
[151 150 151 ... 142 145 148]
[247

[255 255 255 ...  93  92  87]
[184 195 184 ... 128 129 128]
[104 102 101 ... 155 154 152]
[242 245 251 ... 233 232 238]
[230 214 214 ... 198 200 208]
[255 254 255 ... 255 255 255]
[236 235 237 ...  78  78  73]
[207 209 211 ...  68  66  62]
[75 70 71 ... 53 56 72]
[140 126 121 ...  62  60  58]
[  7   6   4 ... 109 109 113]
[ 89 101  81 ...  80  74  58]
[156 154 158 ...  81  82  81]
[156 198 224 ...  71 143 168]
[ 77  77  78 ... 210 209 208]
[253 249 250 ... 238 252 255]
[158 162 162 ...  82  83  80]
[222 227 227 ... 131 129 126]
[128 107 112 ... 177 179 182]
[254 248 223 ... 243 251 251]
[ 82  77  75 ... 114 110  93]
[ 74  75  77 ... 133 141 166]
[104 113 130 ... 227 225 227]
[51 51 54 ... 72 59 58]
[237 211 173 ...  55  62  68]
[145 170 173 ... 129 109  96]
[255 250 246 ... 137 137 136]
[199 201 206 ...  35  22  12]
[240 241 246 ...  59  65  65]
[255 255 255 ... 255 255 255]
[166 173 160 ... 220 221 234]
[251 250 250 ...  64  73  77]
[ 86  85  71 ... 117 117 122]
[113 125 125 ... 106  

[ 98 100 113 ... 103 102 105]
[255 254 254 ... 255 255 255]
[209 207 188 ...  88  93  89]
[232 229 229 ...  71  64  68]
[ 71  65  53 ... 140 139 138]
[225 229 229 ...  90  82  64]
[255 254 255 ... 120 110  94]
[ 28  31  41 ... 160 160 160]
[144 150 152 ... 118 125 126]
[238 238 234 ... 148 150 149]
[239 233 237 ...  91  89  99]
[69 77 90 ... 54 57 61]
[251 249 250 ... 142 137 135]
[ 50  48  47 ... 111 105 100]
[243 243 245 ...  53 101 120]
[175 162 152 ...  77  83  95]
[255 255 255 ... 116 126 131]
[253 255 255 ... 148 155 163]
[214 154 186 ...  36  30  25]
[18 20 21 ... 42 45 47]
[ 79  53  47 ... 159 157 152]
[165 157 141 ...   1   1   1]
[154  92 117 ... 208 214 232]
[221 224 229 ... 153 164 172]
[252 250 251 ... 244 243 244]
[213 210 215 ...  63  60  57]
[217 217 218 ... 110 110 110]
[75 11 37 ... 68 74 79]
[ 45  63  81 ... 218 212 202]
[ 33  37  48 ...  99  99 101]
[183 183 183 ...  92  90  93]
[182 156 156 ...  73  67  75]
[255 255 255 ...  14  16  15]
[164 171 159 ...   4   4   5

[222 207 226 ... 185 190 234]
[236 237 236 ... 101  92  94]
[ 86  81  64 ... 125 121 109]
[186 184 180 ...  57  55  56]
[111 113 116 ... 164 157 149]
[22 25 25 ... 34 25 40]
[205 207 211 ...  97  97  96]
[150 150 152 ...  77  76  76]
[113 139 156 ...  62  73  77]
[234 237 241 ... 218 218 221]
[105  93  86 ...  48  91 103]
[244 237 236 ...  38  37  38]
[163 174 174 ... 239 236 231]
[212 216 224 ...  35  30  29]
[253 251 252 ... 253 253 254]
[232 229 233 ...  96  92  91]
[133 120 144 ...  46  41  43]
[ 52  72  59 ... 224 233 237]
[255 255 255 ... 255 255 255]
[230 230 230 ... 144 146 146]
[97 95 96 ... 23 21 22]
[ 71  84  94 ... 104 103 101]
[55 41 38 ... 76 72 68]
[147 134 122 ... 148 149 148]
[205 222 237 ...  98 100 104]
[182 180 182 ... 136 145 136]
[52 59 69 ... 14  7  3]
[248 246 248 ... 189 190 197]
[210 208 211 ... 193 192 189]
[239 243 245 ... 213 213 213]
[255 253 247 ... 177 192 202]
[241 247 248 ...  94  92  85]
[ 82 101 203 ... 135 149 142]
[123 139 134 ... 226 227 224]
[214

[ 40  67 104 ... 156 150 149]
[255 255 255 ... 255 255 255]
[248 244 245 ... 152 152 150]
[122 124 126 ... 159 160 161]
[ 58  61  64 ... 107 116 126]
[205 204 209 ... 163 167 167]
[34 34 34 ... 55 57 54]
[165 162 164 ...  65  62  66]
[ 71  75  78 ... 143 134 132]
[127 114 104 ...  67  33  64]
[255 253 253 ...  45  50  65]
[255 252 253 ... 253 253 253]
[209 202 201 ...  69  67  65]
[255 253 254 ... 108 115 129]
[ 42  42  43 ... 152 155 156]
[119 121 125 ...  68  65  64]
[254 252 253 ... 181 213 224]
[ 12  13  10 ... 170 166 160]
[ 65 101  99 ... 173 182 180]
[227 230 233 ... 153 194 192]
[ 58  59  59 ...  71 112 118]
[170 175 183 ...  29  27  30]
[ 28   4   0 ... 103 100  99]
[105 105 105 ...  71  69  72]
[100 138 195 ...  55  62  63]
[ 68  68  68 ... 106 104 111]
[0 0 0 ... 0 0 0]
[234 227 228 ... 109 109 103]
[255 255 255 ... 254 254 255]
[118 115  91 ... 123 123 127]
[ 10   9  10 ... 216 211 196]
[ 96  90 122 ...  58  56  55]
[153 142 126 ...  48  46  40]
[ 57  56  72 ...  77  90 114

[253 253 253 ... 253 253 253]
[207 170 185 ... 189 190 180]
[245 246 248 ...  85  87  81]
[ 42  40  34 ... 145 142 144]
[ 78 116  68 ...  36  35  35]
[254 251 251 ... 254 254 254]
[98 98 99 ... 57 59 65]
[180 181 186 ...  87  83  80]
[240 237 237 ...  70  60  47]
[92 91 94 ... 96 94 99]
[255 255 255 ... 227 224 222]
[217 216 217 ...  93 106 137]
[203 160 138 ... 146 139 142]
[100  99 101 ... 115 113 114]
[129 153 150 ... 139 137 133]
[255 255 255 ... 190 222 224]
[ 10  18  20 ... 139 142 144]
[219 206 212 ... 218 219 219]
[253 251 250 ... 252 251 252]
[63 62 62 ... 77 77 78]
[85 83 84 ... 18 18 20]
[210 169 138 ... 151 154 155]
[ 60  65  70 ... 166 161 160]
[238 244 252 ...  70  69  75]
[216 228 228 ... 184 211 225]
[254 251 251 ...  88 152 137]
[202 193 194 ... 151 155 230]
[126 127 129 ... 104 100 100]
[255 253 241 ...  58 186 242]
[ 49  49  54 ... 100 101 102]
[250 248 248 ... 111 110 109]
[207 209 208 ... 194 195 193]
[255 255 255 ... 253 254 255]
[158 160 165 ... 110 103 118]
[253

[115 121 155 ...  36  38  45]
[204 201 201 ...  76  74  75]
[248 251 255 ... 107 104 104]
[139 120 106 ...  25  46  43]
[255 254 254 ... 177 190 188]
[233 230 231 ...  51  56  28]
[206 210 214 ...  71  69  75]
[70 72 86 ...  6 12 32]
[254 251 252 ... 114 113 112]
[ 77  99  98 ... 208 204 198]
[203 176 150 ...  40  42  39]
[ 90  94 101 ...  58  58  59]
[ 92  87  88 ... 170 168 161]
[109 108 110 ... 190 186 184]
[88 87 86 ... 29 29 27]
[255 255 255 ...  48  96 127]
[116 122 123 ... 107 102 103]
[ 65  67  69 ... 129 111 125]
[205 211 201 ... 105 144 165]
[255 255 255 ... 255 255 255]
[255 253 253 ... 133 134 133]
[255 252 253 ...  45  45  46]
[ 95 110 126 ... 165 164 165]
[171 134 120 ...  82  88 100]
[228 228 229 ...  40  39  37]
[252 250 250 ... 126 119 126]
[150 157 161 ... 217 217 215]
[254 251 252 ... 251 252 255]
[160 159 160 ...  14  14  28]
[237 229 225 ... 153 153 153]
[82 75 72 ... 77 83 83]
[255 252 252 ...  47  54  50]
[214 214 220 ... 183 152 131]
[234 232 231 ...  68  69  78

[217 221 224 ... 129 123 116]
[ 77  77  77 ...  90 100 116]
[255 252 253 ... 253 253 253]
[132 128 126 ...  79  84  89]
[132 129 136 ... 167 160 156]
[244 243 241 ... 101 116 128]
[255 253 253 ... 255 255 255]
[204 190 180 ... 176 174 178]
[113 120 101 ... 146 153 144]
[255 252 252 ... 253 254 255]
[235 245 249 ... 143 141 136]
[213 196 192 ...  64  57  59]
[60 54 44 ... 54 43 45]
[57 60 63 ... 78 75 75]
[255 253 254 ... 254 254 254]
[125 124 123 ... 120 118 119]
[182 180 181 ...  97  97  95]
[255 254 254 ... 115 112 112]
[255 255 255 ... 146 112 225]
[240 237 237 ... 142 148 148]
[163 173 173 ... 180 187 182]
[77 70 65 ... 73 78 78]
[106 105 106 ...  28  28  26]
[196 157 157 ... 107 104 100]
[89 89 88 ... 97 97 99]
[112 110 110 ... 145 142 141]
[173 152 106 ... 202 200 198]
[155 146 143 ... 140 134 131]
[ 98 103 112 ... 103 106 120]
[219 225 232 ... 129 115 102]
[254 254 252 ...   7   8   7]
[252 255 255 ... 151 153 151]
[247 248 250 ... 124 120 146]
[255 253 254 ... 114 114 107]
[ 80

[221 218 218 ... 127 135 140]
[246 248 251 ... 151 151 144]
[172 171 175 ... 146 146 145]
[132  78  77 ... 136 135 133]
[177 176 176 ... 110 113 116]
[ 95 108 118 ... 162 160 157]
[255 253 253 ...  81  88 127]
[253 253 239 ... 253 252 252]
[241 239 243 ... 111 106 102]
[  3   3   3 ... 187 183 178]
[ 56  57  64 ...  94 106  74]
[213 220 222 ... 121 122 121]
[1 2 3 ... 5 6 6]
[ 31  32  33 ... 100  90  99]
[136 136 136 ...  42  42  38]
[171 201 202 ... 107 102  95]
[ 53  23  37 ... 137 133 130]
[115 106 109 ...  61  60  59]
[103 152 141 ...  87  97 128]
[252 251 251 ... 147 146 150]
[ 13  15  40 ... 111 110 110]
[255 250 251 ...  54  48  46]
[210 208 209 ... 145 145 146]
[251 245 185 ... 143 144 142]
[213 240 247 ... 139 154 155]
[106 139 142 ...  81 121 153]
[184 185 186 ...  79  85 109]
[223 224 227 ...  77  70  59]
[252 251 252 ...  88  84  78]
[245 240 244 ...  96  93  97]
[134  99 120 ... 195 195 196]
[ 59  87 101 ... 106 104 101]
[207 187 186 ... 105 106 106]
[239 236 237 ... 234 2

[178 156 159 ... 145 144 151]
[80 70 61 ... 65 59 75]
[93 53 54 ... 90 50 34]
[ 52  65  64 ... 157 152 149]
[ 65  85 107 ...  83  88  86]
[175 169 168 ...  93  94  94]
[73 79 81 ... 99 83 82]
[18 30 31 ... 34 35 35]
[115 111 120 ...  80  81  90]
[208 210 208 ... 133 133 135]
[249 243 233 ...  28  26  29]
[155 159 161 ...  38  37  36]
[ 43  36  30 ... 100  78  80]
[ 90  72 111 ... 166 164 162]
[139 138 144 ... 170 166 161]
[242 238 239 ...   8   6   7]
[144 135 132 ...  68  76  65]
[ 38  64  32 ... 110 104  97]
[182 181 173 ... 134 136 130]
[209 208 196 ... 136 127 144]
[144 142 150 ... 101 110  91]
[107 137 137 ...  87  78  75]
[171 163 158 ...  68  67  69]
[177 214 203 ...  97  93  85]
[190 167 161 ... 239 240 250]
[159 157 153 ...  70  58  53]
[ 78  73  91 ... 151 152 155]
[ 4  5 18 ... 22 21 12]
[ 32  44  56 ...  93 119 122]
[ 82  84  96 ... 121 115 122]
[145 149 151 ...  74  70  62]
[46 46 47 ...  8 12 15]
[136 138 123 ...  43  29  35]
[255 255 255 ... 254 253 254]
[49 51 53 ... 51

[161 192 223 ...  43  31  28]
[127 127 128 ... 100 111  95]
[ 95  93  95 ... 176 174 175]
[ 80 102 123 ...  38  43  39]
[72 74 76 ... 55 63 65]
[127 127 127 ... 100  94  83]
[201 216 209 ...  29  45  59]
[127 131 132 ...  66  62  64]
[137 128 123 ...  56  60  70]
[244 238 245 ... 237 241 247]
[13 14 14 ... 73 88 86]
[78 84 89 ... 56 59 81]
[ 74  78  66 ... 193 188 177]
[248 174 138 ... 116 115 112]
[81 82 92 ... 32 23 16]
[136 107 121 ...  42  47  50]
[118 115 114 ... 226 223 232]
[109 113 116 ...  82  78  79]
[226 226 222 ... 202 212 234]
[236 238 240 ... 217 220 230]
[166 200 205 ...  88  83 103]
[  4   3   5 ... 129 142 138]
[49 48 53 ... 60 54 61]
[64 52 63 ... 81 76 70]
[173 159 138 ... 142 142 143]
[ 28  32  40 ... 117 111 144]
[70 48 41 ... 77 64 43]
[ 42  40  33 ...  98 100  97]
[253 251 246 ...  66  66  70]
[20 29 32 ... 28 19 15]
[54 41 52 ... 91 94 88]
[130  46  57 ...  59  51  82]
[77 81 72 ... 21 17 34]
[137 142 151 ...  48  35  50]
[ 3  5  6 ... 68 47 66]
[ 68  72  86 ...

[224 137 113 ... 226 228 241]
[137 143 139 ...  88 100  96]
[21 24 24 ... 19 21 28]
[ 75  95 131 ... 115 116 123]
[121 127 119 ... 111  78  74]
[175 176 177 ... 240 232 219]
[ 28  27  26 ... 217 217 217]
[62 64 71 ... 27 24 27]
[173 159 173 ...  87  85  85]
[206 202 202 ...  74  53  53]
[ 80  78  74 ... 166 178 180]
[82 83 80 ... 49 47 43]
[ 87  95 100 ...  57  21  21]
[143 134 119 ...   1   1   1]
[ 89 100  76 ... 152 145 135]
[20 19 21 ... 51 69 41]
[64 63 64 ... 92 91 86]
[191 211 221 ... 109 102  99]
[20 20 18 ... 47 44 37]
[65 64 62 ... 90 93 82]
[78 75 56 ... 79 81 83]
[255 255 255 ...  91  95  99]
[ 74  82  74 ... 108 101  93]
[ 24  23  22 ... 105  85  88]
[15 17 14 ... 31 39 45]
[167 163 176 ... 115 109 104]
[ 51  54  51 ... 161 138 143]
[ 47  33  51 ...  95  88 100]
[28  1  0 ... 78 82 74]
[107 120 131 ...  97  91  87]
[102  45  60 ... 116 205 193]
[155 158 166 ... 104  96  89]
[28 34 46 ... 30 30 36]
[ 90 107 135 ...  24  33  39]
[123 111 102 ... 104 103  99]
[ 54  47  46 ...

[ 34  39  36 ...  99 119 116]
[ 57  45  32 ... 124 125 113]
[159 176 194 ... 139 141 137]
[144 149 161 ... 210 210 210]
[ 30  28  40 ... 120 119 115]
[ 50  47  50 ... 135 127 138]
[ 30  22  23 ... 119 124 101]
[49 56 86 ... 72 71 68]
[136 121 124 ...  91 104  96]
[ 41  42  47 ... 183 173 165]
[240 237 239 ... 233 237 243]
[118 117 122 ...  62  60  69]
[115  97  88 ... 187 163 162]
[ 20  22  21 ... 174 171 168]
[ 39  38  44 ... 154 154 151]
[133 132 132 ...  95  86  71]
[196 198 200 ... 157 144 145]
[55 46 40 ... 76 74 73]
[ 85  90  97 ... 187 186 183]
[66 70 66 ... 59 65 69]
[160 166 170 ...  70  60  61]
[  4   3   1 ...  97 102  93]
[100  90  84 ... 138 103 100]
[153 221 211 ... 132 157 142]
[61 62 65 ... 73 66 64]
[107 111 102 ...  98  99  99]
[70 70 72 ... 40 64 26]
[137 154 153 ...  83  84  81]
[124 123 124 ... 113 104 103]
[97 94 89 ... 86 83 73]
[ 91  86  77 ... 154 148 127]
[122 124 127 ...  73  72  63]
[ 84  86 121 ...  42  40  43]
[155 162 146 ...  71  64  69]
[ 28  63  59 ...

[129 124 122 ...  69  78  80]
[177 175 167 ...  75  76  48]
[67 75 79 ... 33 31 26]
[255 255 255 ...  55  55  55]
[69 64 66 ... 38 80 89]
[ 22  21  20 ... 116 108  87]
[ 47  47  48 ... 130 134 148]
[57 54 47 ... 47 41 42]
[203 204 207 ... 181 156 138]
[14 18 31 ... 62 68 71]
[10 20 10 ... 44 40 38]
[15 20 11 ... 80 73 69]
[ 88 109 118 ... 119 108  79]
[ 60  74  76 ... 141 160  99]
[83 71 68 ... 55 67 72]
[28 46 26 ... 64 68 68]
[113 118 101 ... 126 111 113]
[ 69  74  97 ... 152 147 139]
[105 118 116 ... 102 106 100]
[108 115 124 ...  74  79  73]
[103 107 133 ... 114 111 123]
[25 23 30 ... 56 46 39]
[154 148  98 ...  60  63 113]
[235 253 249 ...  78  82  87]
[150 160 125 ... 132 135 139]
[32 33 26 ...  8 13  7]
[ 85  95 104 ...  58  57  51]
[53 44 50 ... 54 58 62]
[152 148 124 ...  95  85  74]
[127 132 132 ...  97  96  93]
[126 101  98 ...  75  90  95]
[ 90  90 112 ...  54  69  77]
[ 67  70  93 ... 124 140 127]
[82 65 93 ... 65 48 35]
[75 81 78 ... 56 43 33]
[228 201 208 ... 112 113 171

[99 90 76 ... 44 41 40]
[ 28  23  22 ... 121 119 118]
[ 70  67  80 ... 111 100 126]
[33 40 40 ... 76 75 66]
[166 171 179 ... 148 161 159]
[151  96  80 ... 200 189 191]
[153 160 169 ...  79  79  81]
[  0   0   0 ... 154 162 164]
[28 35 42 ... 63 64 69]
[114 146 147 ... 123 129 128]
[179 182 187 ... 115 116 129]
[24 23 35 ... 68 85 78]
[ 97 106 115 ...  89  85  81]
[154 130 146 ... 103 101 106]
[ 77 114 139 ... 107 125 143]
[167 129  56 ...  94  95  94]
[208 162 157 ... 155 164 185]
[160 153 151 ... 114 113 117]
[ 97 110 109 ... 137 139 140]
[ 52  68  84 ... 135 134 103]
[255 255 255 ... 170  71  55]
[201 197 192 ...  94  71  65]
[164 119 150 ...  45  56  52]
[76 80 75 ... 68 65 68]
[144 144 150 ...  78  94  88]
[121 123 121 ... 100  85  98]
[132 137 116 ... 253 254 254]
[ 39  44  52 ... 123 118 120]
[135 138 140 ... 120 119 110]
[ 33  38  42 ... 237 229 227]
[ 9  7  9 ... 48 46 55]
[76 85 93 ... 26 27 37]
[ 29  31  30 ... 103  91  89]
[61 67 74 ... 73 64 73]
[180 188 189 ...  88  86  84

[105 124 104 ...  26  26  24]
[164 149 144 ...  97  98  91]
[205 205 231 ... 149 158 155]
[183 175 169 ...  69  64  64]
[ 63  64  50 ... 182 182 175]
[121 117 119 ... 112 109 112]
[255 255 255 ... 255 255 255]
[235 230 230 ...  41  49  49]
[151 147 155 ...  68  63  64]
[ 44  50 103 ... 119 104 108]
[ 80  81  80 ... 125 102  77]
[59 62 59 ... 70 64 61]
[168 165 166 ...  77  85  91]
[106 113  99 ... 103  86  97]
[50 53 51 ... 41 43 40]
[60 29 49 ... 17 17 19]
[96 90 69 ... 62 63 63]
[156 157 157 ...  35  33  26]
[122  94  50 ...  57  62  49]
[ 70  96 100 ...  80  85  74]
[104 105 101 ...  30  31  69]
[202 197 197 ... 208 208 208]
[ 35  35  36 ... 182 194 188]
[106 106 128 ... 135 144 146]
[155 156 158 ... 127 122 123]
[201 200 198 ...  52  52  51]
[ 85 105  76 ... 225 216 219]
[39 44 42 ... 54 72 87]
[ 28  27  38 ... 129 146 154]
[234 229 228 ...  34  30  16]
[169 154 152 ... 137 137 139]
[112 116 127 ...  51  54  46]
[ 32  53  70 ... 121 120 121]
[102 114 119 ...  87  86  69]
[  4   2  

# Support Vector Machine